name: messenger_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core: 
  google_sign_in:
  shared_preferences:
  random_string:
  cloud_firestore:
  ffi: ^1.1.2
  file_picker:
  http:
  firebase_storage: 8.0.0   #4.0.0 earlier  10.2.10

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
